name: Generate Doxygen

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run Doxygen
      run: doxygen

    - uses: actions/upload-artifact@v4
    - name: Upload artefacts
      with:
        name: my-artifact
        path: |
          /html
          /latex
